### ISSUE TITLE
Content Update Meeting Notes

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Microservices-architecture#1]
@Microsoft/microsoft-cloud-workshop 

Author suggested updates:
Below is a summary of what we had discussed for the update in our earlier discussions. There are also some subtleties that will be added here in terms of the way we choose to cover AKS setup, Kubernetes features like ingress and load balancing to follow a more "Kubernetes" typical approach (the lab was originally converted from a DC/OS lab which is OK but doesn't fit as naturally in the way we show load balancing setup).
 
Also with the below, I'd like to suggest we use an aspnetcore sample instead of node.js - the value of this lab is more about the platform and devops / containers - the open source story using node.js doesn't seem to be a value add and it would be nice to show how app insights integrates with aspnetcore and how to handle logging, environment overrides, secrets, etc. in aspnetcore.
 
Workshop rewrite:
	• refresh the scenario and associated workshop sample
	• have mongodb migrate to cosmosdb
	• have full ci/cd discussion for containers and environment promotion
	• include secret management
	• include autoscale and load balancing features
 
Lab rewrite:
	• update for new sample - refresh the scenario / idea a little
	• add vsts / ci / cd workflows with azure container registry
	• add cosmosdb work, add back end to sample, show local dev/test and prod migration
	• add secrets
	• add autoscale of nodes + container scale (if possible, AKS may not be positioned to do this yet)
	• add app insights for end to end tracing and visibility
	• update use of kubernetes load balancing and ingress features

SME suggested updates:
Visual Studio connected environment - to Azure Dev Space
http://landinghub.visualstudio.com/devspaces 
	CLI Tool allows to work in backend

Mongo DB to Cosmos DB 
https://blogs.msdn.microsoft.com/alimaz/2018/04/21/migrating-mongodb-databases-from-mongo-lab-to-cosmos-db/ 
	Put in references (WDS) may be too time consuming for lab
	ASPC net core app - starter code with mongo backend (dockerized)
	Lift and shift that to the cloud
	Mongo to Cosmos - modernize the DB - move away from the cluster
	Talking point - functions, options, and reasoning
	
Biggest customer ask - I'd like to deploy AKS using custom vnet on Azure 
	Possible good in Customer needs section
https://docs.microsoft.com/en-us/azure/aks/networking-overview?WT.mc_id=linkedin 

- [ ] Item to do #2

**Comment by sdavis3** [comment]
@waltermyersiii What do you think?

**Comment by DawnmarieDesJardins** [comment]
Closing issue as these were meeting notes.
