### ISSUE TITLE
HOL incorrect abstract

### ISSUE THREAD

**Issue by emilysaeli** [Microsoft/MCW-Microservices-architecture#10]
Abstracts for the HOL step-by-step and unguided, both Infrastructure and Developer editions (four documents in total) are incorrect. They use the WDS abstracts and not the HOL abstracts. The correct abstract appears later but in the incorrect spot.

**Comment by michelebusta** [comment]
I am not sure what the action is here, can someone elaborate on what "incorrect" means?

**Comment by DawnmarieDesJardins** [comment]
Hi Michele!  If you look on the ReadMe page, there's a workshop abstract, a WDS abstract, and a hands-on lab abstract.  In your lab documents, you used the whiteboard design session abstract as the lab abstract, and then put the lab abstract into the Overview section.  We don't have enough technical knowledge to know if we can move those around and still be correct.  Thanks, Dawnamrie

**Comment by michelebusta** [comment]
updated readme, and abstracts for both HOL and design session
