### ISSUE TITLE
Related References links

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-Microservices-architecture#16]
In the [Related References](https://github.com/Microsoft/MCW-Microservices-architecture/tree/august-2018-testfix#related-references), can we update the links for _Technology choices_, _DevOps_ _checklist_ and _Architecture styles_ to point to public URL instead of internal links?

- Technology choices https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-overview
- DevOps checklist https://docs.microsoft.com/en-us/azure/architecture/checklist/dev-ops
- Architecture styles https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/

**Comment by waltermyersiii** [comment]
Fixed.
