### ISSUE TITLE
Update Infra and developer lab guide

### ISSUE THREAD

**Issue by ShivaniThadiyan** [Microsoft/MCW-Microservices-architecture#22]
Exercise 2: Task 5: Setup the function
For function app console is  completely changed in azure portal, please update the lab guide as per new console.

**Comment by ShivaniThadiyan** [comment]
In Developer lab guide:
Exercise 3: Task 5: Setup the function
For function app console is completely changed in azure portal, please update the lab guide as per new console.

**Comment by DawnmarieDesJardins** [comment]
Hi ShivaniThadiyan!
This workshop has been updated and you should be able to complete.  Closing this issue, please let us know if you need further assistance.
