### ISSUE TITLE
Nov test/fix 

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Microservices-architecture#24]
@givenscj 
Hi Chris,

I've merged the November test/fix with the master and will update the HTML files next.  There are two potential security vulnerabilities flagging this workshop.  Please review and respond as needed.

https://github.com/Microsoft/MCW-Microservices-architecture/network/alerts

There is also open issue #22 that was probably addressed during your test/fix.  Please review the issue and respond/close as appropriate.

Thanks.

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris - any update for me on this one?
Thanks, Dawnmarie

**Comment by givenscj** [comment]
The Function app (upgrade to v2) was fixed in the last update.  Can you send the security issue via email.  I can't see it via the link above.

**Comment by DawnmarieDesJardins** [comment]
Completed.  Security issue no longer showing, HTML pages updated.
Thanks Chris!
