### ISSUE TITLE
May 2019 Content Update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Microservices-architecture#28]
Hello,
This workshop is scheduled for a May 2019 update.  Please review open issues #6 #7 and #27 and give your suggested updates for SME review.
Thanks,
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @kylebunting 
Hi gents.  Assigning to you as I can't assign to Zoiner.  I need update suggestions please.

**Comment by DawnmarieDesJardins** [comment]
Per our recent discussion, please move forward with the May update to include:
1) address any existing open issues, 
2) move the workshop away from stateful services
3) add more containerization into the scenario

**Comment by givenscj** [comment]
Adding here for scheduling purposes:

-Update CosmosDB UI screenshots and support new features
-Update the code (nuget update) to support the latest service fabric versions (WebPI)

**Comment by DawnmarieDesJardins** [comment]
Closing with May 2019 content update.
