### ISSUE TITLE
.Net version update

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/MCW-Microservices-architecture#30]
**Is your feature request related to a problem? Please describe.**
Microsoft announced that .net framework 4.8 is the last major version of .net framework. Next .net version will be .net 5, but will be based on .net core. It will be nice to have source code updated to address such announcements from Microsoft. 

https://devblogs.microsoft.com/dotnet/introducing-net-5/
https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

**Describe the solution you'd like**
.net core based application, or at least .net framework 4.8

**Comment by DawnmarieDesJardins** [comment]
Closing as addressed in May 2019 content update.

**Comment by SychevIgor** [comment]
It was not addressed. update was to .net 4.6.1 not to .net core or .net 4.8(not yet released)
