### ISSUE TITLE
Are you able to upload the source code for reference please?

### ISSUE THREAD

**Issue by vishalvatsal** [Microsoft/MCW-Microservices-architecture#4]
Hi Team,

I did go through the docs and found that you have provided a link to source code on Dropbox. It would be great if you can commit it here though.

Thank you

**Comment by amazaheri** [comment]
And I get 404 when trying to reference the dropbox link.

**Comment by michelebusta** [comment]
Are you in the June-2018-updates branch? the link is a bit.ly not dropbox anymore so please tell me where you are seeing this?

**Comment by amazaheri** [comment]
So turned out when I forked couple of days ago there was only Master :) I am getting the June-2018 unless I missed it we should let folks know to target the June branch. Thanks for checking

**Comment by amazaheri** [comment]
Perhaps following initial comment we can add source code as sub-module here?

**Comment by michelebusta** [comment]
Do we want to create a folder in this repo for the source? Is that what you mean? We could do that but in that case the instructions still ask you to download, unzip, etc. That ok?

**Comment by amazaheri** [comment]
I guess perhaps as SME or contributor we can have access to separate repo to contribute if needed.

**Comment by waltermyersiii** [comment]
Hi all. No separate repos. I will start an email trail on this.

**Comment by vishalvatsal** [comment]
Thank you Team :)
