### ISSUE TITLE
Replace manual steps with ARM template

### ISSUE THREAD

**Issue by DivineOps** [microsoft/MCW-Microservices-architecture#7]
In the HOL, Exercise 1, Tasks 2, 4-7 (infra edition) or 2-6 (developer edition) can be easily accomplished with deploying a predefined Azure Resource Manager template, which would save attendees time and allow them to focus on the more substantive parts of the workshop.

**Comment by michelebusta** [comment]
I think we can look at doing this in another update or rewrite. Anything that changes the flow of the labs requires a decent amount of work to create and test and now that we have two labs (dev and infra) this would not fit in scope of this quick turnaround.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue as the workshop will be retired effected 12/31/19.
